**Python Numpy**

In [ ]:
import numpy as np

***1. Numpy Arrays***

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

(1) Array - To create arrays

In [ ]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

(2) arange - To create array (low, high, distance)

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

(3)zeros and ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

(4) linspace(min, max, divide)

In [ ]:
np.linspace(0,5,10)               # 10 even space for range 0-5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

(5) eye

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

(6) Random 


> rand (uniform distribuition)

In [ ]:
np.random.rand(5)        # random samples from a Uniformly distribution from 0 to 1

array([0.98345758, 0.64458691, 0.11789174, 0.80375461, 0.2394476 ])

In [ ]:
np.random.rand(5,5)        # 2-d

array([[0.96828746, 0.01786653, 0.1882678 , 0.10560088, 0.84689566],
       [0.28858078, 0.04650912, 0.14270915, 0.70894485, 0.65812646],
       [0.70348864, 0.51313704, 0.48985154, 0.06498862, 0.85393904],
       [0.53220383, 0.77454358, 0.13995141, 0.57170825, 0.65388785],
       [0.97324456, 0.71471859, 0.62952071, 0.9980485 , 0.12269254]])



> randn (standard normal distribution)



In [ ]:
np.random.randn(2)      # random samples from a standard normal distribution center around 0

array([ 0.48356265, -0.70085027])

In [ ]:
np.random.randn(4,4)      # 2-d

array([[-0.1453796 ,  0.230623  ,  0.13207613, -1.15160317],
       [ 1.6371345 , -0.95955389,  0.7643339 , -2.35785566],
       [ 0.31131406, -1.10058221, -0.27945262, -2.17477584],
       [-0.47233892, -0.11432326,  1.48338518, -0.15834048]])



> randint (min, max, quantity)



In [ ]:
np.random.randint(1,100,10)

array([62, 27,  5, 61, 94, 82, 20, 39, 15, 27])

(7) reshape

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)          # 5 * 5 = 25 (elements)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

(8) max, min, argmax, argmin

In [ ]:
ranarr = np.random.randint(0,50,10)
ranarr

array([32, 40, 48, 10, 28, 10,  0, 40, 47, 32])

In [ ]:
ranarr.max()

48

In [ ]:
ranarr.min()

0

In [ ]:
ranarr.argmax()        # index location of the max value

2

In [ ]:
ranarr.argmin()

6

(9) shape, dtype

In [ ]:
arr.shape         # this is a 1-d array

(25,)

In [ ]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

(10) import ... randint

In [ ]:
from numpy.random import randint

In [ ]:
randint(2,10)

7

***2. Numpy Array Indexing***

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

(1) pick up the elements



> One dimension



In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[5:]        # start from the element 6

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

*Be careful: If don't use copy method, the original array will be changed*

In [ ]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr         # change also occur in the original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])



> 2 dimension


In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[0][0]      # first row first column

5

In [ ]:
arr_2d[0]     # first row

array([ 5, 10, 15])

In [ ]:
arr_2d[2][1]

40

In [ ]:
arr_2d[2,1]     # same as [2][1]

40

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [75]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

(2) Conditional Selection

In [77]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [81]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [82]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [83]:
arr[arr < 3]

array([1, 2])

In [84]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

***3. Numpy Operations***

In [88]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

(1) Array with Array / Scalars

In [89]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [90]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [92]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [93]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [94]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [95]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [96]:
1 / arr      # gets infinity instead of nan

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [97]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

(2) Universal Array Function (ufunc)

In [98]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [99]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [100]:
np.max(arr)

10

In [101]:
arr.max()

10

In [102]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [103]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])